### ISSUE TITLE
Request of small changes

### ISSUE THREAD

**Issue by ghost** [bplu4t2f/Windows10PhotoViewerSucksAss#2]
Hi. First I would like to say thank you for a simple and useful program. 
I wanted to use the program on a public computer and came across the fact that the program name is displayed in the extended program selection list for file types and also in appdata the program creates a folder with its name. As you know, the program have unusual name and I wouldn't want anyone to see it. If it's not too much trouble, could you please attach a binary package to the next release with name for example "Photo Viewer" and make all possible paths of the program have that name? 
It would also be great if you made a script for a simpler association of the program with pictures files.

**Comment by bplu4t2f** [comment]
File associations are on the imaginary TODO list. It's not so simple because I dont' want to mess up anything with the existing file classes in Windows. I fear it could possibly break image preview in Windows Explorer for example.

I will try to make it so that the name of the executable file is displayed in all dialogs, and is also the name used in %LOCALAPPDATA% to store the user's settings.
